[build.environment]
  NODE_VERSION = "18"
[build]
  publish = "docs/.vitepress/dist"
  command = "pnpm run docs:build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF docs package.json pnpm-lock.yaml netlify.toml"
